//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FastFoodFinder.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FastFoodFinder.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info.
        /// </summary>
        public static string AboutMenuItemText {
            get {
                return ResourceManager.GetString("AboutMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed and published by FK Engineering. .
        /// </summary>
        public static string AboutPageCopyrightText {
            get {
                return ResourceManager.GetString("AboutPageCopyrightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Fast Food Finder allowes you to find Fast Food around your current position..
        /// </summary>
        public static string AboutPageDescriptionText {
            get {
                return ResourceManager.GetString("AboutPageDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutPageTitle {
            get {
                return ResourceManager.GetString("AboutPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: .
        /// </summary>
        public static string AboutPageVersionText {
            get {
                return ResourceManager.GetString("AboutPageVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Food Finder.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        public static string DefaultZoomLevel {
            get {
                return ResourceManager.GetString("DefaultZoomLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to getting location....
        /// </summary>
        public static string GettingLocationProgressText {
            get {
                return ResourceManager.GetString("GettingLocationProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to suche....
        /// </summary>
        public static string GettingPOIProgressText {
            get {
                return ResourceManager.GetString("GettingPOIProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to locate me.
        /// </summary>
        public static string LocateMeMenuButtonText {
            get {
                return ResourceManager.GetString("LocateMeMenuButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow.
        /// </summary>
        public static string LocationAllowButtonText {
            get {
                return ResourceManager.GetString("LocationAllowButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string LocationCancelButtonText {
            get {
                return ResourceManager.GetString("LocationCancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current location cannot be obtained. Check that location service is turned on in phone settings..
        /// </summary>
        public static string LocationDisabledMessageBoxText {
            get {
                return ResourceManager.GetString("LocationDisabledMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please decide....
        /// </summary>
        public static string LocationUsageInfoText {
            get {
                return ResourceManager.GetString("LocationUsageInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Fast Food Finder to access and use your location?.
        /// </summary>
        public static string LocationUsageQueryText {
            get {
                return ResourceManager.GetString("LocationUsageQueryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your location.
        /// </summary>
        public static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current location not available..
        /// </summary>
        public static string NoCurrentLocationMessageBoxText {
            get {
                return ResourceManager.GetString("NoCurrentLocationMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location information not found..
        /// </summary>
        public static string NoInfoMessageBoxText {
            get {
                return ResourceManager.GetString("NoInfoMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No match found. Narrow your search e.g. &quot;Seattle Wa&quot;..
        /// </summary>
        public static string NoMatchFoundMessageBoxText {
            get {
                return ResourceManager.GetString("NoMatchFoundMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to burger+king.
        /// </summary>
        public static string SearchStringBurgerKing {
            get {
                return ResourceManager.GetString("SearchStringBurgerKing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jim+block.
        /// </summary>
        public static string SearchStringJimBlock {
            get {
                return ResourceManager.GetString("SearchStringJimBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kentucky+fried+chicken.
        /// </summary>
        public static string SearchStringKFC {
            get {
                return ResourceManager.GetString("SearchStringKFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mcdonalds.
        /// </summary>
        public static string SearchStringMcDonalds {
            get {
                return ResourceManager.GetString("SearchStringMcDonalds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nordsee.
        /// </summary>
        public static string SearchStringNordsee {
            get {
                return ResourceManager.GetString("SearchStringNordsee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to starbucks.
        /// </summary>
        public static string SearchStringStarbucks {
            get {
                return ResourceManager.GetString("SearchStringStarbucks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subway.
        /// </summary>
        public static string SearchStringSubway {
            get {
                return ResourceManager.GetString("SearchStringSubway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vapiano.
        /// </summary>
        public static string SearchStringVapiano {
            get {
                return ResourceManager.GetString("SearchStringVapiano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://open.mapquestapi.com/nominatim/v1/search.php.
        /// </summary>
        public static string SearchURL {
            get {
                return ResourceManager.GetString("SearchURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsMenuButtonText {
            get {
                return ResourceManager.GetString("SettingsMenuButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burger King.
        /// </summary>
        public static string UserFriendlyNameBurgerKing {
            get {
                return ResourceManager.GetString("UserFriendlyNameBurgerKing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jim Block.
        /// </summary>
        public static string UserFriendlyNameJimBlock {
            get {
                return ResourceManager.GetString("UserFriendlyNameJimBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kentucky Fried Chicken.
        /// </summary>
        public static string UserFriendlyNameKFC {
            get {
                return ResourceManager.GetString("UserFriendlyNameKFC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mc Donald&apos;s.
        /// </summary>
        public static string UserFriendlyNameMcDonalds {
            get {
                return ResourceManager.GetString("UserFriendlyNameMcDonalds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nordsee.
        /// </summary>
        public static string UserFriendlyNameNordsee {
            get {
                return ResourceManager.GetString("UserFriendlyNameNordsee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starbucks.
        /// </summary>
        public static string UserFriendlyNameStarbucks {
            get {
                return ResourceManager.GetString("UserFriendlyNameStarbucks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subway.
        /// </summary>
        public static string UserFriendlyNameSubway {
            get {
                return ResourceManager.GetString("UserFriendlyNameSubway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vapiano.
        /// </summary>
        public static string UserFriendlyNameVapiano {
            get {
                return ResourceManager.GetString("UserFriendlyNameVapiano", resourceCulture);
            }
        }
    }
}
